import { colors } from "./constants";

export const styles: { [key: string]: React.CSSProperties } = {
    container: {
        fontFamily: "'Inter', 'Segoe UI', 'Roboto', sans-serif",
        minHeight: "100vh",
        background: colors.bgPrimary,
        display: "flex",
        flexDirection: "column",
        color: colors.textPrimary,
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "16px 32px",
        background: colors.bgSecondary,
        borderBottom: `1px solid ${colors.borderPrimary}`,
    },
    headerContent: {
        display: "flex",
        alignItems: "center",
        gap: 16,
    },
    logoContainer: {
        display: "flex",
        alignItems: "center",
        gap: 12,
    },
    logoIcon: {
        fontSize: 28,
        color: colors.accent,
        fontWeight: 700,
    },
    logo: {
        fontSize: 24,
        fontWeight: 700,
        color: colors.textPrimary,
        margin: 0,
        letterSpacing: "-0.5px",
    },
    headerRight: {
        display: "flex",
        alignItems: "center",
        gap: 12,
    },
    connectedBadge: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        background: colors.bgTertiary,
        padding: "8px 16px",
        borderRadius: 8,
        color: colors.textPrimary,
        fontSize: 13,
        border: `1px solid ${colors.borderPrimary}`,
    },
    connectedDot: {
        width: 8,
        height: 8,
        borderRadius: "50%",
        background: colors.success,
        boxShadow: `0 0 8px ${colors.success}`,
    },
    disconnectBtn: {
        background: colors.bgTertiary,
        color: colors.textSecondary,
        border: `1px solid ${colors.borderPrimary}`,
        padding: "8px 16px",
        borderRadius: 8,
        cursor: "pointer",
        fontSize: 13,
        transition: "all 0.2s",
    },
    errorBox: {
        background: colors.dangerBg,
        color: colors.danger,
        padding: "12px 24px",
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: 14,
        borderBottom: `1px solid ${colors.danger}`,
    },
    errorClose: {
        marginLeft: "auto",
        background: "none",
        border: "none",
        color: colors.danger,
        fontSize: 20,
        cursor: "pointer",
    },

    // Connect View
    connectContainer: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "40px 20px",
    },
    connectCard: {
        background: colors.bgCard,
        borderRadius: 16,
        padding: "48px",
        textAlign: "center",
        boxShadow: `0 20px 60px rgba(0,0,0,0.5)`,
        border: `1px solid ${colors.borderPrimary}`,
        maxWidth: 420,
        width: "100%",
    },
    connectIconWrapper: {
        width: 80,
        height: 80,
        borderRadius: "50%",
        background: colors.accentGlow,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        margin: "0 auto 24px",
        border: `2px solid ${colors.accent}`,
    },
    connectIconInner: {
        fontSize: 36,
    },
    connectTitle: {
        fontSize: 24,
        fontWeight: 600,
        color: colors.textPrimary,
        margin: "0 0 8px 0",
    },
    connectSubtitle: {
        color: colors.textSecondary,
        fontSize: 14,
        margin: "0 0 32px 0",
    },
    connectForm: {
        display: "flex",
        flexDirection: "column",
        gap: 16,
    },
    connectSelect: {
        padding: "14px 16px",
        borderRadius: 10,
        border: `1px solid ${colors.borderSecondary}`,
        fontSize: 14,
        outline: "none",
        background: colors.bgInput,
        color: colors.textPrimary,
        cursor: "pointer",
    },
    connectButton: {
        background: colors.accent,
        color: "#fff",
        border: "none",
        padding: "14px",
        borderRadius: 10,
        fontSize: 15,
        fontWeight: 600,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    refreshLink: {
        background: "none",
        border: "none",
        color: colors.textMuted,
        marginTop: 20,
        cursor: "pointer",
        fontSize: 13,
        transition: "color 0.2s",
    },
    featuresGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: 20,
        marginTop: 48,
        maxWidth: 700,
        width: "100%",
    },
    featureCard: {
        background: colors.bgCard,
        border: `1px solid ${colors.borderPrimary}`,
        borderRadius: 12,
        padding: "28px 20px",
        textAlign: "center",
    },
    featureIconWrapper: {
        fontSize: 32,
        marginBottom: 12,
    },
    featureTitle: {
        fontSize: 16,
        fontWeight: 600,
        margin: "0 0 8px 0",
        color: colors.textPrimary,
    },
    featureDesc: {
        fontSize: 13,
        color: colors.textMuted,
        margin: 0,
        lineHeight: 1.5,
    },

    // Main Content
    mainContent: {
        flex: 1,
        padding: "24px 32px",
    },
    statsRow: {
        display: "grid",
        gridTemplateColumns: "repeat(4, 1fr)",
        gap: 16,
        marginBottom: 24,
    },
    statCard: {
        background: colors.bgCard,
        borderRadius: 12,
        padding: "24px 20px",
        textAlign: "center",
        border: `1px solid ${colors.borderPrimary}`,
    },
    statNumber: {
        fontSize: 36,
        fontWeight: 700,
    },
    statLabel: {
        fontSize: 13,
        color: colors.textMuted,
        marginTop: 4,
        textTransform: "uppercase",
        letterSpacing: "0.5px",
    },
    twoColumnLayout: {
        display: "grid",
        gridTemplateColumns: "360px 1fr",
        gap: 24,
    },
    leftColumn: {},
    rightColumn: {
        display: "flex",
        flexDirection: "column",
        gap: 24,
    },
    card: {
        background: colors.bgCard,
        borderRadius: 12,
        padding: 24,
        border: `1px solid ${colors.borderPrimary}`,
    },
    cardHeader: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        marginBottom: 20,
        paddingBottom: 16,
        borderBottom: `1px solid ${colors.borderPrimary}`,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 600,
        color: colors.textPrimary,
        margin: 0,
        flex: 1,
    },
    badge: {
        background: colors.accentGlow,
        color: colors.accent,
        padding: "4px 12px",
        borderRadius: 6,
        fontSize: 13,
        fontWeight: 600,
    },
    formGroup: {
        marginBottom: 16,
    },
    formRow: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 12,
    },
    label: {
        display: "block",
        fontSize: 12,
        fontWeight: 500,
        color: colors.textSecondary,
        marginBottom: 8,
        textTransform: "uppercase",
        letterSpacing: "0.5px",
    },
    input: {
        width: "100%",
        padding: "12px 14px",
        borderRadius: 8,
        border: `1px solid ${colors.borderSecondary}`,
        fontSize: 14,
        outline: "none",
        boxSizing: "border-box",
        background: colors.bgInput,
        color: colors.textPrimary,
        transition: "border-color 0.2s",
    },
    collateralPreview: {
        background: colors.warningBg,
        border: `1px solid ${colors.warning}`,
        borderRadius: 8,
        padding: "12px 14px",
        marginBottom: 16,
        fontSize: 13,
        display: "flex",
        justifyContent: "space-between",
        color: colors.warning,
    },
    primaryButton: {
        width: "100%",
        background: colors.accent,
        color: "#fff",
        border: "none",
        padding: "14px",
        borderRadius: 8,
        fontSize: 14,
        fontWeight: 600,
        cursor: "pointer",
        marginTop: 8,
        transition: "all 0.2s",
    },
    emptyState: {
        textAlign: "center",
        padding: "40px 20px",
        color: colors.textMuted,
    },
    emptyIcon: {
        fontSize: 40,
        display: "block",
        marginBottom: 12,
        opacity: 0.5,
    },
    emptyStateSmall: {
        textAlign: "center",
        padding: "24px",
        color: colors.textMuted,
        fontSize: 13,
    },
    loanList: {
        display: "flex",
        flexDirection: "column",
        gap: 12,
        maxHeight: 400,
        overflowY: "auto",
    },
    loanItem: {
        background: colors.bgTertiary,
        borderRadius: 10,
        padding: 16,
        borderLeft: "4px solid",
        borderLeftColor: colors.accent,
    },
    loanItemHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    loanAmount: {
        fontSize: 22,
        fontWeight: 700,
        color: colors.textPrimary,
    },
    statusBadge: {
        padding: "4px 10px",
        borderRadius: 6,
        fontSize: 11,
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: "0.3px",
    },
    loanDetails: {
        display: "flex",
        gap: 16,
        fontSize: 12,
        color: colors.textSecondary,
        marginBottom: 10,
    },
    loanParties: {
        display: "flex",
        flexDirection: "column",
        gap: 4,
        fontSize: 11,
        color: colors.textMuted,
        marginBottom: 14,
    },
    loanActions: {
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
    },
    successBtn: {
        background: colors.success,
        color: "#fff",
        border: "none",
        padding: "8px 16px",
        borderRadius: 6,
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    warningBtn: {
        background: colors.warning,
        color: "#000",
        border: "none",
        padding: "8px 16px",
        borderRadius: 6,
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    dangerBtn: {
        background: colors.danger,
        color: "#fff",
        border: "none",
        padding: "8px 16px",
        borderRadius: 6,
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    twoColumnSmall: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: 24,
    },
    loanListCompact: {
        display: "flex",
        flexDirection: "column",
        gap: 8,
        maxHeight: 250,
        overflowY: "auto",
    },
    loanItemCompact: {
        background: colors.bgTertiary,
        borderRadius: 8,
        padding: 12,
        borderLeft: "3px solid",
    },
    compactHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 6,
    },
    compactAmount: {
        fontSize: 16,
        fontWeight: 600,
        color: colors.textPrimary,
    },
    compactBadge: {
        padding: "3px 8px",
        borderRadius: 4,
        fontSize: 10,
        fontWeight: 600,
        textTransform: "uppercase",
    },
    compactDetail: {
        fontSize: 11,
        color: colors.textMuted,
    },
    footer: {
        textAlign: "center",
        padding: "20px",
        color: colors.textMuted,
        fontSize: 13,
        borderTop: `1px solid ${colors.borderPrimary}`,
        background: colors.bgSecondary,
    },
};
